/CS 360
//2-20-15
////Program: compiles files for you
//
//
//#include <stdio.h>
//#include <stdlib.h>
//#include <sys/stat.h>
//#include <string.h>
//
//
//#include "fields.h"
//#include "dllist.h"
//#include "jrb.h"
//
//
//int main(int argc, char* argv[]){
//	char* mfile;
//		IS is;
//			Dllist clist,hlist,llist,flist,tmp;
//				int i;	
//					int ex,exists;
//						char* E;
//							struct stat buf;
//								time_t maxtime,ctime,otime,maxotime;	
//									int flaglen,liblen,objlen;
//										char* ofile;
//											int make = 0;
//												char* flags;
//													char* libs;
//														char* compile;
//															int compilelen;
//																int sysret;
//																	char* objs;
//																		char* cfile;
//																			int first = 0;
//																				int numcomps = 0;
//
//																					//Determine where to read instructions from
//																						if( argc == 2){
//																								mfile = argv[1];}
//																									else{
//																											mfile = malloc(10*sizeof(char));
//																													strcpy(mfile,"fmakefile");}
//
//																														//Prepare to read from file, if file cant be read exit
//																															is = new_inputstruct(mfile);
//																																if ( is == NULL){
//																																		perror(argv[1]);
//																																				exit(1);
//																																					}
//																																						
//																																							//Initialize our list of different files
//																																								clist = new_dllist();
//																																									hlist = new_dllist();
//																																										llist = new_dllist();
//																																											flist = new_dllist();
//																																												ex = 0;
//
//																																													//Set lengths of strings
//																																														flaglen = 0;
//																																															liblen = 0;
//																																																objlen = 0;
//																																																	
//																																																		//Begin reading from file
//																																																			//If blank line skip
//																																																				//If not check first field, if its a valid letter, begin appending files to list
//																																																					//Track executable, if more than one exit
//																																																						while( get_line(is) >= 0){
//																																																								if(is->NF == 0){}
//																																																										else if(strcmp(is->fields[0],"C") == 0){
//																																																													for( i = 1; i < is->NF ; i++){
//																																																																	objlen = objlen + strlen(is->fields[i]) + 1;
//																																																																					dll_append(clist, new_jval_s(strdup(is->fields[i])));
//																																																																								}	
//																																																																										}
//																																																																												else if(strcmp(is->fields[0],"H") == 0){
//																																																																															for( i = 1; i < is->NF ; i++){
//																																																																																			dll_append(hlist, new_jval_s(strdup(is->fields[i])));
//																																																																																						}	
//																																																																																								}
//																																																																																										else if(strcmp(is->fields[0],"L") == 0){
//																																																																																													for( i = 1; i < is->NF ; i++){
//																																																																																																	liblen = liblen + strlen(is->fields[i]) + 1;
//																																																																																																					dll_append(llist, new_jval_s(strdup(is->fields[i])));
//																																																																																																								}	
//																																																																																																										}
//																																																																																																												else if(strcmp(is->fields[0],"E") == 0){
//																																																																																																															if(ex == 1){
//																																																																																																																			fprintf(stderr,"fmakefile (%d) cannot have more than one E line\n",is->line);
//																																																																																																																							exit(1);}
//																																																																																																																										E = strdup(is->fields[1]);
//																																																																																																																													ex = 1;
//																																																																																																																															}
//																																																																																																																																	else if(strcmp(is->fields[0],"F") == 0){
//																																																																																																																																				for( i = 1; i < is->NF ; i++){
//																																																																																																																																								flaglen = flaglen + strlen(is->fields[i]) + 1;
//																																																																																																																																												dll_append(flist, new_jval_s(strdup(is->fields[i])));
//																																																																																																																																															}	
//																																																																																																																																																	}
//																																																																																																																																																			else{
//																																																																																																																																																						fprintf(stderr,"Invalid line\n");
//																																																																																																																																																									exit(1);
//																																																																																																																																																											}
//																																																																																																																																																												}
//
//																																																																																																																																																													//If no executable exit
//																																																																																																																																																														if(ex == 0){
//																																																																																																																																																																fprintf(stderr,"No executable specified\n");
//																																																																																																																																																																		exit(1);}
//
//																																																																																																																																																																			//Make sure all the h files exist, and find the latest mod-time
//																																																																																																																																																																				maxtime = 0;
//																																																																																																																																																																					dll_traverse(tmp,hlist){
//																																																																																																																																																																							exists = stat(jval_s(tmp->val),&buf);
//																																																																																																																																																																									if(exists < 0){
//																																																																																																																																																																												fprintf(stderr,"no h file\n");
//																																																																																																																																																																															exit(1);}
//
//																																																																																																																																																																																	if(buf.st_mtime > maxtime){
//																																																																																																																																																																																				maxtime = buf.st_mtime;}
//																																																																																																																																																																																					}
//
//
//
//
//
//
//																																																																																																																																																																																					H
//
//
//																																																																																																																																																																																						//Allocate space for strings	
//																																																																																																																																																																																							flags = malloc(flaglen*sizeof(char));
//																																																																																																																																																																																								libs = malloc(liblen*sizeof(char));
//																																																																																																																																																																																									objs = malloc(objlen*sizeof(char));
//
//																																																																																																																																																																																										//Set up flag string
//																																																																																																																																																																																											dll_traverse(tmp,flist){
//																																																																																																																																																																																													if(first== 0){
//																																																																																																																																																																																																strcpy(flags,tmp->val.s);
//																																																																																																																																																																																																			first = 1;}
//																																																																																																																																																																																																					else{
//																																																																																																																																																																																																								sprintf(flags,"%s %s",flags,tmp->val.s);}
//																																																																																																																																																																																																									}
//
//																																																																																																																																																																																																										//Set up lib string
//																																																																																																																																																																																																											first = 0;
//																																																																																																																																																																																																												dll_traverse(tmp,llist){
//																																																																																																																																																																																																														if(first== 0){
//																																																																																																																																																																																																																	strcpy(libs,tmp->val.s);
//																																																																																																																																																																																																																				first = 1;}
//																																																																																																																																																																																																																						else{
//																																																																																																																																																																																																																									sprintf(libs,"%s %s",libs,tmp->val.s);}
//																																																																																																																																																																																																																										}
//
//
//																																																																																																																																																																																																																											first = 0;
//																																																																																																																																																																																																																												maxotime = 0;
//
//																																																																																																																																																																																																																													//Traverse C files
//																																																																																																																																																																																																																														dll_traverse(tmp,clist){
//																																																																																																																																																																																																																																//Make sure file exists, if not exit
//																																																																																																																																																																																																																																		exists = stat(jval_s(tmp->val),&buf);
//																																																																																																																																																																																																																																				if(exists < 0){
//																																																																																																																																																																																																																																							fprintf(stderr,"fmakefile: %s: No such file or directory\n",tmp->val.s);
//																																																																																																																																																																																																																																										exit(1);}
//																																																																																																																																																																																																																																												
//																																																																																																																																																																																																																																														//Get the c file time, c file name, and ofile name
//																																																																																																																																																																																																																																																ctime = buf.st_mtime;
//																																																																																																																																																																																																																																																		ofile = strdup(jval_s(tmp->val));
//																																																																																																																																																																																																																																																				cfile = strdup(jval_s(tmp->val));
//																																																																																																																																																																																																																																																						ofile[strlen(ofile) - 1] = 'o';
//																																																																																																																																																																																																																																																								
//																																																																																																																																																																																																																																																										//Check if the o file needs to be remade
//																																																																																																																																																																																																																																																												//Will be made if it doesnt exist
//																																																																																																																																																																																																																																																														//Or if the cfile is newer
//																																																																																																																																																																																																																																																																exists = stat(ofile,&buf);
//																																																																																																																																																																																																																																																																		if(exists < 0){
//																																																																																																																																																																																																																																																																					make = 1;}
//																																																																																																																																																																																																																																																																							else{
//																																																																																																																																																																																																																																																																										otime = buf.st_mtime;}
//																																																																																																																																																																																																																																																																												if( otime > maxotime){
//																																																																																																																																																																																																																																																																															maxotime = otime;}
//																																																																																																																																																																																																																																																																																	if( ctime > otime || maxtime > otime){
//																																																																																																																																																																																																																																																																																				make = 1;}
//																																																																																																																																																																																																																																																																																						
//																																																																																																																																																																																																																																																																																								//If we need to make the file
//																																																																																																																																																																																																																																																																																										//Make the proper string
//																																																																																																																																																																																																																																																																																												//Make a system call, and check to be sure it works
//																																																																																																																																																																																																																																																																																														if(make==1){
//																																																																																																																																																																																																																																																																																																	numcomps = numcomps + 1;
//																																																																																																																																																																																																																																																																																																				if(flaglen == 0){
//																																																																																																																																																																																																																																																																																																								compile = malloc((8 + strlen(ofile))*sizeof(char));
//																																																																																																																																																																																																																																																																																																												sprintf(compile,"gcc -c %s",cfile);}
//																																																																																																																																																																																																																																																																																																															else{
//																																																																																																																																																																																																																																																																																																																			compile = malloc((9 + strlen(ofile)+flaglen)*sizeof(char));
//																																																																																																																																																																																																																																																																																																																							sprintf(compile,"gcc -c %s %s",flags,cfile);}
//																																																																																																																																																																																																																																																																																																																										printf("%s\n",compile);
//																																																																																																																																																																																																																																																																																																																													sysret = system(compile);
//																																																																																																																																																																																																																																																																																																																																if(sysret != 0){
//																																																																																																																																																																																																																																																																																																																																				fprintf(stderr, "Command failed.  Exitting\n");
//																																																																																																																																																																																																																																																																																																																																								exit(1);}
//																																																																																																																																																																																																																																																																																																																																											free(compile);
//																																																																																																																																																																																																																																																																																																																																													}
//																																																																																																																																																																																																																																																																																																																																															
//																																																																																																																																																																																																																																																																																																																																																	//Add ofile to string
//																																																																																																																																																																																																																																																																																																																																																			if( first == 0){
//																																																																																																																																																																																																																																																																																																																																																						strcpy(objs,ofile);
//																																																																																																																																																																																																																																																																																																																																																									first = 1;}
//																																																																																																																																																																																																																																																																																																																																																											else{
//																																																																																																																																																																																																																																																																																																																																																														sprintf(objs,"%s %s",objs,ofile);}
//																																																																																																																																																																																																																																																																																																																																																																
//																																																																																																																																																																																																																																																																																																																																																																		free(ofile);
//																																																																																																																																																																																																																																																																																																																																																																				free(cfile);
//																																																																																																																																																																																																																																																																																																																																																																						make = 0;
//																																																																																																																																																																																																																																																																																																																																																																							}
//
//																																																																																																																																																																																																																																																																																																																																																																								//Determine if we need to make the executable
//																																																																																																																																																																																																																																																																																																																																																																									make = 0;	
//																																																																																																																																																																																																																																																																																																																																																																										exists = stat(E,&buf);
//																																																																																																																																																																																																																																																																																																																																																																											if(exists < 0){
//																																																																																																																																																																																																																																																																																																																																																																													make = 1;}
//																																																																																																																																																																																																																																																																																																																																																																														if(maxotime > buf.st_mtime){
//																																																																																																																																																																																																																																																																																																																																																																																make = 1;}
//																																																																																																																																																																																																																																																																																																																																																																																	if(numcomps != 0){
//																																																																																																																																																																																																																																																																																																																																																																																			make = 1;}
//
//																																																																																																																																																																																																																																																																																																																																																																																				char executable[10000];
//																																																																																																																																																																																																																																																																																																																																																																																					
//																																																																																																																																																																																																																																																																																																																																																																																						//If we do then construct the correct string
//																																																																																																																																																																																																																																																																																																																																																																																							//Make a system call with the string
//																																																																																																																																																																																																																																																																																																																																																																																								//Make sure the call succeeds
//																																																																																																																																																																																																																																																																																																																																																																																									if( make == 1){
//																																																																																																																																																																																																																																																																																																																																																																																											
//																																																																																																																																																																																																																																																																																																																																																																																													if(liblen == 0 && flaglen == 0){
//																																																																																																																																																																																																																																																																																																																																																																																																sprintf(executable,"gcc -o %s %s",E,objs);
//																																																																																																																																																																																																																																																																																																																																																																																																			printf("%s\n",executable);
//																																																																																																																																																																																																																																																																																																																																																																																																						sysret =system(executable);
//																																																																																																																																																																																																																																																																																																																																																																																																									if(sysret != 0){
//																																																																																																																																																																																																																																																																																																																																																																																																													fprintf(stderr,"Command failed.  Fakemake exiting\n");
//																																																																																																																																																																																																																																																																																																																																																																																																																	exit(1);}
//																																																																																																																																																																																																																																																																																																																																																																																																																			}
//																																																																																																																																																																																																																																																																																																																																																																																																																					else if(liblen == 0){
//																																																																																																																																																																																																																																																																																																																																																																																																																								sprintf(executable,"gcc -o %s %s %s",E,flags,objs);
//																																																																																																																																																																																																																																																																																																																																																																																																																											printf("%s\n",executable);
//																																																																																																																																																																																																																																																																																																																																																																																																																														sysret = system(executable);
//																																																																																																																																																																																																																																																																																																																																																																																																																																	if(sysret!= 0){
//																																																																																																																																																																																																																																																																																																																																																																																																																																					fprintf(stderr,"Command failed.  Fakemake exiting\n");
//																																																																																																																																																																																																																																																																																																																																																																																																																																									exit(1);}
//																																																																																																																																																																																																																																																																																																																																																																																																																																											}
//																																																																																																																																																																																																																																																																																																																																																																																																																																													else if(flaglen == 0){
//																																																																																																																																																																																																																																																																																																																																																																																																																																																sprintf(executable,"gcc -o %s %s %s",E,objs,libs);
//																																																																																																																																																																																																																																																																																																																																																																																																																																																			printf("%s\n",executable);
//																																																																																																																																																																																																																																																																																																																																																																																																																																																						sysret = system(executable);
//																																																																																																																																																																																																																																																																																																																																																																																																																																																									if(sysret!= 0){
//																																																																																																																																																																																																																																																																																																																																																																																																																																																													fprintf(stderr,"Command failed.  Fakemake exiting\n");
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																	exit(1);}
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																			}
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																					else{
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																								sprintf(executable,"gcc -o %s %s %s %s",E,flags,objs,libs);
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																											printf("%s\n",executable);
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																														sysret = system(executable);
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																	if(sysret!= 0){
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																					fprintf(stderr,"Command failed.  Fakemake exiting\n");
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																									exit(1);}
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																											}
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																												}
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																													//If we dont need to make an executable, exit	
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																														else if(make == 0){
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																printf("%s up to date\n",E);
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																		exit(1);}
//
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																			//Clear memmory
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																				/*	
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																					jettison_inputstruct(is);
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						
//
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																							dll_traverse(tmp,flist){
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																									free(tmp->val.s);}
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										free_dllist(flist);
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																											
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																												dll_traverse(tmp,hlist){
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																														free(tmp->val.s);}
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																															free_dllist(hlist);
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																	dll_traverse(tmp,clist){
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																			free(tmp->val.s);}
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																				free_dllist(clist);
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																					
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						dll_traverse(tmp,llist){
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																								free(tmp->val.s);}
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																									free_dllist(llist);
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																									*/	
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										exit(0);
//																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										}
//
//
//
